version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  load-csv:
    build: ./load-csv
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    networks:
      - default

  airflow-init:
    build: ./airflow
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "Waiting for Postgres..."
        sleep 10
        airflow db upgrade
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=YOUR_GENERATED_FERNET_KEY_HERE
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./tests:/opt/airflow/tests
      - ./include:/opt/airflow/include
    depends_on:
      - postgres

  airflow-scheduler:
    build: ./airflow
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=YOUR_GENERATED_FERNET_KEY_HERE
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./tests:/opt/airflow/tests
      - ./include:/opt/airflow/include
    command: scheduler

  airflow-webserver:
    build: ./airflow
    restart: always
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=YOUR_GENERATED_FERNET_KEY_HERE
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./tests:/opt/airflow/tests
      - ./include:/opt/airflow/include
    command: webserver

  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN='' # ปิด token
      - JUPYTER_PASSWORD='' # ปิด password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

volumes:
  postgres_data:

networks:
  default:
